---
apache_service: apache2
apache_daemon: apache2
apache_daemon_path: /usr/sbin/
apache_server_root: /etc/apache2
apache_conf_path: /etc/apache2

__apache_packages:
  - apache2
  - apache2-utils
  - libpcre3-dev
  - libapache2-mod-php8.2
  - libapache2-mod-wsgi-py3

apache_ports_configuration_items:
  - regexp: "^Listen "
    line: "Listen {{ apache_listen_port }}"
