# Local Root directory of repository
root_dir: "{{ lookup('file', 'sensitive/root_dir') }}"

# Source directory on Local computer
source_directory: "{{ root_dir }}/starter-architecture/server"

# Domain of your site
domain: "{{ lookup('file', 'sensitive/domain_name') }}"

# Where site will be located
domain_path: "/var/www/html/{{ domain }}"

# Where releases will be located
releases_dir: "{{ domain_path }}/releases"

# Where link to current release will be located
current_dir: "{{ domain_path }}/current"

# Where directory with persistent data will be located
persistent_dir: "{{ domain_path }}/persistent"

# Run migrations
migrate: true

# Command to run migrations
# Alternatives: php artisan migrate:refresh --seed
migrate_command: php artisan migrate --force

# Command to rollback migrations
migrate_rollback_command: php artisan migrate:rollback --force

# Backup database before migration
# spatie/laravel-backup should be installed in your project
backup_db: false

# Validate your .env file
# melihovv/laravel-env-validator should be installed in your project
validate_env: false